### ISSUE TITLE
Auth went wrong

### ISSUE THREAD

**Issue by HiDiHo01** [DCSBL/python-frank-energie#68]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.frank_energie.coordinator
Source: C:\Program Files\HassWP_2023.3.6\python-3.11.3.amd64\Lib\site-packages\homeassistant\helpers\update_coordinator.py:354
Integration: Frank Energie (documentation, issues)
First occurred: 17:46:38 (8 occurrences)
Last logged: 20:07:07

Unexpected error fetching Frank Energie coordinator data:
Traceback (most recent call last):
  File "C:\Program Files\HassWP_2023.3.6\python-3.11.3.amd64\Lib\site-packages\homeassistant\helpers\update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\HassWP_2023.3.6\config\custom_components\frank_energie\coordinator.py", line 65, in _async_update_data
    await self.api.month_summary() if self.api.is_authenticated else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\HassWP_2023.3.6\python-3.11.3.amd64\Lib\site-packages\python_frank_energie\frank_energie.py", line 123, in month_summary
    return MonthSummary.from_dict(await self._query(query))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\HassWP_2023.3.6\python-3.11.3.amd64\Lib\site-packages\python_frank_energie\frank_energie.py", line 57, in _query
    raise AuthException
python_frank_energie.exceptions.AuthException

**Comment by DCSBL** [comment]
Wat is er precies “aangepast”? Heb je een codevoorbeeld met wat dit heeft getriggerd?

**Comment by HiDiHo01** [comment]
> Wat is er precies “aangepast”? Heb je een codevoorbeeld met wat dit heeft getriggerd?

De originele laatste code v2.4.1 + api 5.0.0
Enige dat ik heb aangepast is de manifest.json
    "requirements": [
        "python-frank-energie==5.0.0"
    ],

en in de coordinator.py 2 regels ivm snake_case variable in api
line 65: await self.api.month_summary() if self.api.is_authenticated else None
line 97: :user_prices = await self.api.user_prices(start_date)

**Comment by DCSBL** [comment]
Fixed with https://github.com/bajansen/home-assistant-frank_energie/pull/84
